spring:
  application:
    name: reaktor-strikesServer
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_strikesserver?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8091

logging:
  level:
      root: INFO
  file:
      name: /tmp/reaktor_eventsServer.log
      max-size: 1MB
      max-history: 10
      total-size-cap: 10MB
reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  urlCors: https://somos.iesjandula.es
  printers_server_url: https://api.iesjandula.es/
  firebase_server_url: https://api.iesjandula.es/
  notifications_server_url: https://api.iesjandula.es/
  school_base_server_url: https://api.iesjandula.es/
  clientId: ${CLIENT_ID}
  http_connection_timeout: 30000
  scriptCreacionConsultaHuelga: https://script.google.com/macros/s/AKfycbw6_P8MN2DD3S9TkBTow29iTeKOviE0oPmdtrisd3kYGE4dMhLUnuyLyjGXRzNVjCSHIw/exec
  scriptBorradoHuelga: https://script.google.com/macros/s/AKfycbywUgI6wpxu-kfaPl8rKgW90EsBDcMr_n-8X0bq_f1IoonzoDGxAX4Y7Ff0SauqKlMtWQ/exec
  audit:
    exchange: audit.exchange
    routing-key: audit.key