spring:
  application:
    name: strikes
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_strikesserver?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8091
  
logging:
  level:
    root: INFO
  file:
    name: C:\logs\Strikes.log
    max-size: 1MB
    max-history: 10
    total-size-cap: 10MB

reaktor:
  publicKeyFile: C:\claves\public_key.pem
  urlCors: http://localhost:5173, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173
  printers_server_url: http://localhost:8082/
  firebase_server_url: http://localhost:8083/
  notifications_server_url: http://localhost:8088/
  school_base_server_url: http://localhost:8093/
  clientId: strikes
  http_connection_timeout: 30000
  reiniciarParametros: true
  scriptCreacionConsultaHuelga: https://script.google.com/macros/s/AKfycbzmqvPz-vxcNUVwTbkKVIp6XaaIM53UQAqzkFvKQNPjjLh1AcBic4Kdd9jWff6GMIS-3w/exec
  scriptBorradoHuelga: https://script.google.com/macros/s/AKfycbywUgI6wpxu-kfaPl8rKgW90EsBDcMr_n-8X0bq_f1IoonzoDGxAX4Y7Ff0SauqKlMtWQ/exec
  audit:
    exchange: audit.exchange
    routing-key: audit.key

