spring:
  jpa.hibernate.ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_strikesserver?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8091

logging:
  level:
      root: INFO
  file:
      name: /tmp/reaktor_eventsServer.log
      max-size: 1MB
      max-history: 10
      total-size-cap: 10MB
reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  urlCors: https://somos.iesjandula.es
  printers_server_url: https://api.iesjandula.es/
  firebase_server_url: https://api.iesjandula.es/
  notifications_server_url: https://api.iesjandula.es/
  school_base_server_url: https://api.iesjandula.es/
  clientId: ${CLIENT_ID}
  http_connection_timeout: 30000
  plantillaFormulario: https://script.google.com/macros/s/AKfycbxBZMx9zV8tmk15DDtmf5bXA9xOzGSaZCtk65E6TorKkUoTfezQJd3PwgkaWNrsLGq05A/exec
